general:
  require_stations_in_aoi: true
  timezone: Europe/Rome

meteo_data:
  handler: province_api
  stations: ['19300MS', '69900MS', '09700MS', '82200MS']

base_grid:
  path: "https://files.isimip.org/ISIMIP3a/InputData/climate/atmosphere/obsclim/global/daily/historical/CHELSA-W5E5/chelsa-w5e5_obsclim_orog_30arcsec_global.nc#mode=bytes"
  var: orog
  crs: 4326
  target_crs: 32532
  aoi_buffer_m: 5000

aoi:
  minx: 10
  miny: 46
  maxx: 12
  maxy: 47

interpolation:
  vertical_model:
    type: linear
    fit_intercept: True

  distance:
    type: path_distance
    connectivity_type: 4
    lam_values: [0, 25, 50, 75, 100, 150, 200]
    max_visibility_distance: null
    cache_directory: data/cache/distances

  inverse_distance_weighting:
    neighbours: 4
    weight_exponent: 2

output:
  format: tiff
  options:
    path: data/results